# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Success is a Journey, not a Destination'
tagline:             ''
description:         'TODO: define a direction when the time comes.'
url:                 http://blog.intransient.info
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ken Kawamoto
  url:               https://twitter.com/imsuten

# Custom vars
version:             1.0.0
